name: Nightly Releases

# Cron scheduling
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

on:
  schedule:
    # Every day at 7pm UTC / 2pm CST
    # - cron: '0 19 * * *'
    - cron: '*/5 * * * *'

jobs:
  release_nightly_canary:
    name: Release Nightly Canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # https://github.com/atlassian/changesets/blob/master/docs/snapshot-releases.md
      - name: Release to NPM
        run: |
          npm run version:nightly
          npm run release:nightly
